name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-cache
        with:
          caching: false
          cache-path: node_modules
          cache-key: "${{ hashFiles('package-lock.json') }}"
      - name: Lint code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-cache
        with:
          caching: false
          cache-path: node_modules
          cache-key: "${{ hashFiles('package-lock.json') }}"
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        uses: ./.github/actions/install-cache
        with:
          caching: false
          cache-path: node_modules
          cache-key: "${{ hashFiles('package-lock.json') }}"
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: http://gh-actions-course.mariusmihai.org
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      # - id: deploy
      #   name: Run Javascript Custom Action
      #   uses: ./.github/actions/deploy-s3
      #   with:
      #     app-folder: ./dist
      #     bucket-region: us-east-1
      #     bucket-name: gh-actions-course.mariusmihai.org
      #   env:
      #     AWS_REGION: ${{ secrets.AWS_REGION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - id: deploy
        name: Run Docker Custom Action
        uses: ./.github/actions/deploy-s3-docker
        with:
          app-folder: ./dist
          bucket-region: us-east-1
          bucket-name: gh-actions-course.mariusmihai.org
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: echo "${{ toJSON(steps.deploy.outputs) }}"
